### ISSUE TITLE
Angular 5 [...]\node_modules\@infinitycube\gravatar\src\gravatar.service.ts is not part of the compilation output

### ISSUE THREAD

**Issue by jakehockey10** [infinitycube/gravatar#4]
I upgraded my Angular app to version 5 (seemingly correctly), but now I'm getting errors I don't know what to do with pointing towards gravatar.  The error message is: 

```
ERROR in ./node_modules/@infinitycube/gravatar/src/gravatar.directive.ts
Module build failed: Error: C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@infinitycube\gravatar\src\gravatar.directive.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:648:23)
    at plugin.done.then (C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/@infinitycube/gravatar/index.js 5:27-62
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./node_modules/@infinitycube/gravatar/src/gravatar.module.ts
Module build failed: Error: C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@infinitycube\gravatar\src\gravatar.module.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:648:23)
    at plugin.done.then (C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/@infinitycube/gravatar/index.js 7:24-56
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./node_modules/@infinitycube/gravatar/src/gravatar.service.ts
Module build failed: Error: C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@infinitycube\gravatar\src\gravatar.service.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:648:23)
    at plugin.done.then (C:\Users\j.smith\Documents\src\TeamDigital\tdportal\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/@infinitycube/gravatar/index.js 3:25-58
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
```

I'm not sure what I did to break this as it was working before.  But I did notice that there are no js files in the node_modules/@infinitycube/gravatar folder.  So I ran `tsc` on the folder, which gave me some js files in the src folder.  But I can't get the index.ts file to transpile.  Even with the command `tsc index.ts` while in the root directory of this node module.

Do you know what might be going wrong?  What can I do?  Thanks

**Comment by jakehockey10** [comment]
It looks like angular 5 is using more strict typescript rules and the errors are stemming from not being able to find the JavaScript instead of the typescript

**Comment by gopumon** [comment]
A new version with all *.js files in `bundles` directory and a new .npmignore file created for not to publish *.ts files. It will resolve the Angular 5 issue.
